"""Database creation

Revision ID: 702a4222d54a
Revises: e60d9d65f90f
Create Date: 2025-09-10 23:55:14.066322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '702a4222d54a'
down_revision: Union[str, None] = 'e60d9d65f90f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('d_create', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('d_change', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_auth_email'), 'user_auth', ['email'], unique=True)
    op.create_index(op.f('ix_user_auth_id'), 'user_auth', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_auth_id'), table_name='user_auth')
    op.drop_index(op.f('ix_user_auth_email'), table_name='user_auth')
    op.drop_table('user_auth')
    # ### end Alembic commands ###
