version: '3.8'

services:
  fastapi-app:
    container_name: app
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./.env:/app/.env
    environment:
      - ENVIRONMENT=development
    env_file: .env
    restart: unless-stopped
    depends_on:
      - db
      - redis  # ← добавляем зависимость от Redis
    
  db:
    image: postgres:15
    container_name: db
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  
  redis:  # ← новый сервис Redis
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning

volumes:
  postgres_data:
  redis_data:  # ← том для Redis